//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.SaMacDanhSaches = new HashSet<SaMacDanhSach>();
        }
    
        public int Id { get; set; }
        public RoleList Role { get; set; }
        public string CapBac { get; set; }
        public int DoanId { get; set; }
        public int MienId { get; set; }
        public string SaintName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Gender { get; set; }
        
        public virtual Doan Doan { get; set; }
        public virtual ICollection<SaMacDanhSach> SaMacDanhSaches { get; set; }
    }
}
