//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doan
    {
        public Doan()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int Id { get; set; }
        public int MienId { get; set; }
        public Nullable<int> LienDoanId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ChaTuyenUy { get; set; }
        public Nullable<int> DoanTruong { get; set; }
        public Nullable<int> PhoQuanTri { get; set; }
        public Nullable<int> PhoNghienHuan { get; set; }
        public Nullable<int> ThuKy { get; set; }
        public Nullable<int> ThuQuy { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Status { get; set; }
        public string ParishName { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual LienDoan LienDoan { get; set; }
        public virtual Mien Mien { get; set; }
    }
}
