//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mien
    {
        public Mien()
        {
            this.Doans = new HashSet<Doan>();
            this.LienDoans = new HashSet<LienDoan>();
            this.SaMacs = new HashSet<SaMac>();
        }
    
        public int Id { get; set; }
        public int TruongUongId { get; set; }
        public MienList Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ChaTuyenUy { get; set; }
        public Nullable<int> ChuTich { get; set; }
        public Nullable<int> PhoQuanTri { get; set; }
        public Nullable<int> PhoNghienHuan { get; set; }
        public Nullable<int> ThuKy { get; set; }
        public Nullable<int> ThuQuy { get; set; }
        public Nullable<int> UyVienAu { get; set; }
        public Nullable<int> UyVienThieu { get; set; }
        public Nullable<int> UyVienNghia { get; set; }
        public Nullable<int> UyVienHiep { get; set; }
        public Nullable<int> UyVienKyThuat { get; set; }
        public Nullable<int> UyVienPhungVu { get; set; }
        public Nullable<int> UyVienTruyenThong { get; set; }
        public Nullable<int> UyVienGiaoTe { get; set; }
        public Nullable<int> UyVienDaiHoi { get; set; }
        public Nullable<int> UyVienBaoChi { get; set; }
        public Nullable<int> UyVienVanNghe { get; set; }
        public Nullable<int> UyVienXaHoi { get; set; }
        public Nullable<int> UyVienTaiChanh { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Doan> Doans { get; set; }
        public virtual ICollection<LienDoan> LienDoans { get; set; }
        public virtual TrungUong TrungUong { get; set; }
        public virtual ICollection<SaMac> SaMacs { get; set; }
    }
}
