//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace TNTT.Model
{
    using System;
    
    public enum MienList : int
    {
        [Description("Miền Tây Bắc")]
        MienTayBac = 1,
        [Description("Miền Tây")]
        MienTay = 2,
        [Description("Miền Tây Nam")]
        MienTayNam = 3,
        [Description("Miền Nam")]
        MienNam = 4,
        [Description("Miền Trung")]
        MienTrung = 5,
        [Description("Miền Trung Đông")]
        MienTrungDong = 6,
        [Description("Miền Đông Bắc")]
        MienDongBac = 7,
        [Description("Miền Đông Nam")]
        MienDongNam = 8
    }
}
