//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace TNTT.Model
{
    using System;
    
    public enum RoleList : int
    {
        [Description("Tuyên Úy")]
        TuyenUy = 1,
        [Description("Trợ Úy")]
        TroUy = 2,
        [Description("Trợ Tá")]
        TroTa = 3,
        [Description("Huynh Trưởng")]
        HuynhTruong = 4,
        [Description("Huấn Luyện Viên")]
        HuanLuyenVien = 5
    }
}
