//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaMacDanhSach
    {
        public int SaMacId { get; set; }
        public int ContactId { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Mentor { get; set; }
        public Nullable<bool> Completion { get; set; }
        public string TienSaMac { get; set; }
        public string HauSaMac { get; set; }
        public Nullable<bool> Pass { get; set; }
        public Nullable<bool> ThangCap { get; set; }
        public Nullable<System.DateTime> ThangCapDate { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual SaMac SaMac { get; set; }
    }
}
