//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaMac
    {
        public int Id { get; set; }
        public Nullable<int> MienId { get; set; }
        public Nullable<int> LienDoanId { get; set; }
        public string SaMacCode { get; set; }
        public string SaMacName { get; set; }
        public Nullable<int> ChaTuyenUy { get; set; }
        public Nullable<int> SaMacTruong { get; set; }
        public Nullable<int> SaMacPho { get; set; }
        public Nullable<int> KhoaTruong { get; set; }
        public int ContactPerson { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> SaMacStartDate { get; set; }
        public Nullable<System.DateTime> SaMacEndDate { get; set; }
    
        public virtual LienDoan LienDoan { get; set; }
        public virtual Mien Mien { get; set; }
        public virtual SaMacDanhSach SaMacDanhSach { get; set; }
    }
}
