//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.ModelConfiguration.Conventions;

namespace TNTT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TNTTContext : DbContext
    {
        public TNTTContext()
            : base("name=TNTTDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contact> ContactSet { get; set; }
        public DbSet<Doan> DoanSet { get; set; }
        public DbSet<LienDoan> LienDoans { get; set; }
        public DbSet<Mien> MienSet { get; set; }
        public DbSet<SaMac> SaMacSet { get; set; }
        public DbSet<SaMacDanhSach> SaMacDanhSachSet { get; set; }
        public DbSet<TrungUong> TrungUongSet { get; set; }
    }
}
